jy46604790/Fake-News-Bert-Detect model evaluation


In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

folder_path = "./jy46604790_fake_news_bert_detect"

tokenizer = AutoTokenizer.from_pretrained(folder_path)
model = AutoModelForSequenceClassification.from_pretrained(folder_path)


Default model performance on the whole ReNew dataset


In [ ]:
import pandas as pd
import torch
from datasets import Dataset
from transformers import pipeline
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

renew_dataset_path = './ReNew dataset/combined renew dataset.csv'
renew_df = pd.read_csv(renew_dataset_path)

renew_hf_dataset = Dataset.from_pandas(renew_df)

renew_statements = renew_hf_dataset['statement']
renew_true_labels = renew_hf_dataset['label']

fake_news_model_path = "./jy46604790_fake_news_bert_detect"
fake_news_classifier = pipeline(
    "text-classification",
    model=fake_news_model_path,
    tokenizer=fake_news_model_path,
    device=0 if torch.cuda.is_available() else -1
)

renew_predictions_raw = fake_news_classifier(
    renew_statements,
    truncation=True,
    batch_size=32
)

renew_predicted_labels = [1 if pred['label'] == 'LABEL_1' else 0 for pred in renew_predictions_raw]

renew_accuracy = accuracy_score(renew_true_labels, renew_predicted_labels)
renew_f1_score = f1_score(renew_true_labels, renew_predicted_labels)
renew_confusion_matrix = confusion_matrix(renew_true_labels, renew_predicted_labels)

print(f"Accuracy on Renew dataset: {renew_accuracy:.4f}")
print(f"F1 Score on Renew dataset: {renew_f1_score:.4f}")
print("Confusion Matrix (Renew dataset):")
print(renew_confusion_matrix)

Device set to use cuda:0


Accuracy on Renew dataset: 0.5139
F1 Score on Renew dataset: 0.0832
Confusion Matrix (Renew dataset):
[[1294   20]
 [1259   58]]


Default model performance on ReNew test


In [ ]:
import pandas as pd
import torch
from datasets import Dataset
from transformers import pipeline
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

combined_renew_test_csv_path = './ReNew dataset/combined renew train.csv'
combined_renew_test_df = pd.read_csv(combined_renew_test_csv_path)

combined_renew_test_hf_dataset = Dataset.from_pandas(combined_renew_test_df)

test_statements = combined_renew_test_hf_dataset['statement']
test_true_labels = combined_renew_test_hf_dataset['label']

fake_news_model_path = "./jy46604790_fake_news_bert_detect"
fake_news_classifier = pipeline(
    "text-classification",
    model=fake_news_model_path,
    tokenizer=fake_news_model_path,
    device=0 if torch.cuda.is_available() else -1
)

test_predictions_raw = fake_news_classifier(
    test_statements,
    truncation=True,
    batch_size=32
)

test_predicted_labels = [1 if pred['label'] == 'LABEL_1' else 0 for pred in test_predictions_raw]

test_accuracy = accuracy_score(test_true_labels, test_predicted_labels)
test_f1_score = f1_score(test_true_labels, test_predicted_labels)
test_confusion_matrix = confusion_matrix(test_true_labels, test_predicted_labels)

print(f"Accuracy on Combined Renew Test dataset: {test_accuracy:.4f}")
print(f"F1 Score on Combined Renew Test dataset: {test_f1_score:.4f}")
print("Confusion Matrix (Combined Renew Test dataset):")
print(test_confusion_matrix)

Device set to use cuda:0


Accuracy on Combined Renew Test dataset: 0.5123
F1 Score on Combined Renew Test dataset: 0.0919
Confusion Matrix (Combined Renew Test dataset):
[[257   6]
 [251  13]]


Fine tuning with ReNew training to test performance over ReNew testing


In [ ]:
import pandas as pd
from datasets import Dataset

combined_renew_train_csv_path = './ReNew dataset/combined renew train.csv'
combined_renew_train_df = pd.read_csv(combined_renew_train_csv_path)

combined_renew_train_hf_dataset = Dataset.from_pandas(combined_renew_train_df)

combined_renew_train_hf_dataset


Dataset({
    features: ['label', 'statement'],
    num_rows: 2104
})

In [ ]:
from transformers import RobertaTokenizer, RobertaForSequenceClassification

model_name = "jy46604790/Fake-News-Bert-Detect"
tokenizer = RobertaTokenizer.from_pretrained(model_name)
model = RobertaForSequenceClassification.from_pretrained(model_name, num_labels=2)

model.config, tokenizer

tokenizer_config.json:   0%|          | 0.00/1.14k [00:00<?, ?B/s]

c:\Users\alber\anaconda3\envs\ai-testing\lib\site-packages\huggingface_hub\file_download.py:142: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\alber\.cache\huggingface\hub\models--jy46604790--Fake-News-Bert-Detect. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/735 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

(RobertaConfig {
   "_attn_implementation_autoset": true,
   "_name_or_path": "jy46604790/Fake-News-Bert-Detect",
   "architectures": [
     "RobertaForSequenceClassification"
   ],
   "attention_probs_dropout_prob": 0.1,
   "bos_token_id": 0,
   "classifier_dropout": null,
   "eos_token_id": 2,
   "hidden_act": "gelu",
   "hidden_dropout_prob": 0.1,
   "hidden_size": 768,
   "initializer_range": 0.02,
   "intermediate_size": 3072,
   "layer_norm_eps": 1e-05,
   "max_position_embeddings": 514,
   "model_type": "roberta",
   "num_attention_heads": 12,
   "num_hidden_layers": 12,
   "pad_token_id": 1,
   "position_embedding_type": "absolute",
   "problem_type": "single_label_classification",
   "torch_dtype": "float32",
   "transformers_version": "4.49.0",
   "type_vocab_size": 1,
   "use_cache": true,
   "vocab_size": 50265
 },
 RobertaTokenizer(name_or_path='jy46604790/Fake-News-Bert-Detect', vocab_size=50265, model_max_length=512, is_fast=False, padding_side='right', truncation_side='

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

In [ ]:
def tokenize_function(examples):
    return tokenizer(examples['statement'], padding="max_length", truncation=True)

combined_renew_train_hf_dataset = combined_renew_train_hf_dataset.map(tokenize_function, batched=True)

combined_renew_train_hf_dataset


Map:   0%|          | 0/2104 [00:00<?, ? examples/s]

Dataset({
    features: ['label', 'statement', 'input_ids', 'attention_mask'],
    num_rows: 2104
})

In [ ]:
train_dataset, val_dataset = combined_renew_train_hf_dataset.train_test_split(test_size=0.1).values()

len(train_dataset), len(val_dataset)


(1893, 211)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./bert_fakenews_finetuned",
    evaluation_strategy="no",
    save_strategy="no",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    save_total_limit=1,
    load_best_model_at_end=True,
    metric_for_best_model="eval_f1",
    greater_is_better=True,
    fp16=True,
    report_to="none"
)

c:\Users\alber\anaconda3\envs\ai-testing\lib\site-packages\transformers\training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [13]:
import torch
print("Using GPU:", torch.cuda.is_available())


Using GPU: True


In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
)

trainer.train()

C:\Users\alber\AppData\Local\Temp\ipykernel_25976\3028656916.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(


Step,Training Loss
50,0.296700
100,0.213100
150,0.267800
200,0.266500


TrainOutput(global_step=238, training_loss=0.24778771200099914, metrics={'train_runtime': 4687.7477, 'train_samples_per_second': 0.808, 'train_steps_per_second': 0.051, 'total_flos': 996138455592960.0, 'train_loss': 0.24778771200099914, 'epoch': 2.0})

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

predictions = trainer.predict(val_dataset)
predicted_labels = predictions.predictions.argmax(axis=-1)
ground_truth_labels = predictions.label_ids

accuracy = accuracy_score(ground_truth_labels, predicted_labels)

f1 = f1_score(ground_truth_labels, predicted_labels)

conf_matrix = confusion_matrix(ground_truth_labels, predicted_labels)

print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9005
F1 Score: 0.9058
Confusion Matrix:
[[ 89  14]
 [  7 101]]


In [ ]:
output_dir = "./fine tuned models/jy46_fine_tuned_fake_news_bert"

model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"Model and tokenizer saved to {output_dir}")


Model and tokenizer saved to ./fine tuned models/jy46_fine_tuned_fake_news_bert


Evaluating model performance on my testing dataset


In [ ]:
combined_renew_test_csv_path = './ReNew dataset/combined renew train.csv'
combined_renew_test_df = pd.read_csv(combined_renew_test_csv_path)

combined_renew_test_hf_dataset = Dataset.from_pandas(combined_renew_test_df)

combined_renew_test_hf_dataset = combined_renew_test_hf_dataset.map(tokenize_function, batched=True)

test_predictions = trainer.predict(combined_renew_test_hf_dataset)
test_predicted_labels = test_predictions.predictions.argmax(axis=-1)
test_ground_truth_labels = test_predictions.label_ids

test_accuracy = accuracy_score(test_ground_truth_labels, test_predicted_labels)
test_f1 = f1_score(test_ground_truth_labels, test_predicted_labels)
test_conf_matrix = confusion_matrix(test_ground_truth_labels, test_predicted_labels)

print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"Test F1 Score: {test_f1:.4f}")
print("Test Confusion Matrix:")
print(test_conf_matrix)


Map:   0%|          | 0/527 [00:00<?, ? examples/s]

Test Accuracy: 0.8843
Test F1 Score: 0.8893
Test Confusion Matrix:
[[221  42]
 [ 19 245]]


Testing performance over the original politifact dataset, using the original (default) moodel


In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

folder_path = "./jy46604790_fake_news_bert_detect"

politifact_tokenizer = AutoTokenizer.from_pretrained(folder_path)
politifact_model = AutoModelForSequenceClassification.from_pretrained(folder_path)


In [ ]:
politifact_fake_df = pd.read_csv("./Politifact dataset/politifact kaggle fake.csv")
politifact_true_df = pd.read_csv("./Politifact dataset/politifact kaggle true.csv")

print("Fake News Samples:")
print(politifact_fake_df.head())

print("\nTrue News Samples:")
print(politifact_true_df.head())


Fake News Samples:
                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  

True News Samples:
                                               title  \
0  As U.S. budget fight looms, Republicans fl

In [ ]:
politifact_fake_df["label"] = 0
politifact_true_df["label"] = 1

politifact_combined_df = pd.concat([politifact_fake_df, politifact_true_df], ignore_index=True)

politifact_combined_df = politifact_combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(politifact_combined_df.head())


                                               title  \
0  Ben Stein Calls Out 9th Circuit Court: Committ...   
1  Trump drops Steve Bannon from National Securit...   
2  Puerto Rico expects U.S. to lift Jones Act shi...   
3   OOPS: Trump Just Accidentally Confirmed He Le...   
4  Donald Trump heads for Scotland to reopen a go...   

                                                text       subject  \
0  21st Century Wire says Ben Stein, reputable pr...       US_News   
1  WASHINGTON (Reuters) - U.S. President Donald T...  politicsNews   
2  (Reuters) - Puerto Rico Governor Ricardo Rosse...  politicsNews   
3  On Monday, Donald Trump once again embarrassed...          News   
4  GLASGOW, Scotland (Reuters) - Most U.S. presid...  politicsNews   

                  date  label  
0    February 13, 2017      0  
1       April 5, 2017       1  
2  September 27, 2017       1  
3         May 22, 2017      0  
4       June 24, 2016       1  


In [ ]:

train_df, test_df = train_test_split(
    politifact_combined_df, 
    test_size=0.2, 
    random_state=42,
    stratify=politifact_combined_df["label"]
)

print(f"Training samples: {len(train_df)}")
print(f"Testing samples: {len(test_df)}")

Training samples: 35918
Testing samples: 8980


In [ ]:
import os

os.makedirs("./Politifact dataset/merged", exist_ok=True)

train_file_path = "./Politifact dataset/merged/merged_politifact_train.csv"
test_file_path = "./Politifact dataset/merged/merged_politifact_test.csv"

train_df.to_csv(train_file_path, index=False)
test_df.to_csv(test_file_path, index=False)

print(f"Training dataset saved to: {train_file_path}")
print(f"Testing dataset saved to: {test_file_path}")

Training dataset saved to: ./Politifact dataset/merged/merged_politifact_train.csv
Testing dataset saved to: ./Politifact dataset/merged/merged_politifact_test.csv


In [ ]:
politifact_copy_df = test_df.copy()

politifact_copy_df = politifact_copy_df.rename(columns={"text": "statement"})

politifact_statements = politifact_copy_df['statement'].tolist()
politifact_true_labels = politifact_copy_df['label'].tolist()

print(politifact_copy_df.head())

                                                   title  \
14864  Philippines doctor linked to New York attack p...   
7865   More Republicans expect Clinton, rather than T...   
16749  DEMOCRAT UNDERBELLY EXPOSED: Out-Of-Control Vi...   
29452  Those who boycott Syrian congress may be sidel...   
44890  Burundi opposition platform boycotts new round...   

                                               statement       subject  \
14864  MANILA (Reuters) - A Filipino accused by the U...     worldnews   
7865   NEW YORK (Reuters) - More Republicans now thin...  politicsNews   
16749  Donald Trump on Wednesday slammed what he desc...      politics   
29452  ASTANA (Reuters) - Syrian groups who choose to...     worldnews   
44890  NAIROBI (Reuters) - Burundi s main opposition ...     worldnews   

                     date  label  
14864   October 10, 2017       1  
7865    October 26, 2016       1  
16749        May 25, 2016      0  
29452   October 31, 2017       1  
44890  November 28,

In [ ]:
from transformers import pipeline

fake_news_model_path = "./jy46604790_fake_news_bert_detect"

politifact_fake_news_classifier = pipeline(
    "text-classification",
    model=fake_news_model_path,
    tokenizer=fake_news_model_path,
    device=0 if torch.cuda.is_available() else -1
)

Device set to use cuda:0


In [ ]:
politifact_predictions_raw = politifact_fake_news_classifier(
    politifact_statements,
    truncation=True,
    batch_size=32
)

politifact_predicted_labels = [1 if pred['label'] == 'LABEL_1' else 0 for pred in politifact_predictions_raw]


In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, f1_score

politifact_accuracy = accuracy_score(politifact_true_labels, politifact_predicted_labels)
politifact_f1_score = f1_score(politifact_true_labels, politifact_predicted_labels)
politifact_recall = recall_score(politifact_true_labels, politifact_predicted_labels)
politifact_precision = precision_score(politifact_true_labels, politifact_predicted_labels)

politifact_conf_matrix = confusion_matrix(politifact_true_labels, politifact_predicted_labels)

tn, fp, fn, tp = politifact_conf_matrix.ravel()
politifact_specificity = tn / (tn + fp)

print(f"Accuracy on Politifact dataset: {politifact_accuracy:.4f}")
print(f"Recall on Politifact dataset: {politifact_recall:.4f}")
print(f"Specificity on Politifact dataset: {politifact_specificity:.4f}")
print(f"Precision on Politifact dataset: {politifact_precision:.4f}")
print(f"F1 Score on Politifact dataset: {politifact_f1_score:.4f}")
print("Confusion Matrix (Politifact dataset):")
print(politifact_conf_matrix)

Accuracy on Politifact dataset: 0.9994
Recall on Politifact dataset: 0.9998
Specificity on Politifact dataset: 0.9991
Precision on Politifact dataset: 0.9991
F1 Score on Politifact dataset: 0.9994
Confusion Matrix (Politifact dataset):
[[4692    4]
 [   1 4283]]


Testing performance over the LIAR + Renew fine tuned version


In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

saved_model_path = "./fine tuned models/jy46_fine_tuned_fake_news_bert"

loaded_model = AutoModelForSequenceClassification.from_pretrained(saved_model_path)
loaded_tokenizer = AutoTokenizer.from_pretrained(saved_model_path)

fake_news_classifier = pipeline(
    "text-classification",
    model=loaded_model,
    tokenizer=loaded_tokenizer,
    device=0 if torch.cuda.is_available() else -1
)

Device set to use cuda:0


In [ ]:
politifact_predictions_raw = fake_news_classifier(
    politifact_statements,
    truncation=True,
    batch_size=32
)

politifact_predicted_labels = [1 if pred['label'] == 'LABEL_1' else 0 for pred in politifact_predictions_raw]

politifact_accuracy = accuracy_score(politifact_true_labels, politifact_predicted_labels)
politifact_f1_score = f1_score(politifact_true_labels, politifact_predicted_labels)
politifact_recall = recall_score(politifact_true_labels, politifact_predicted_labels)
politifact_precision = precision_score(politifact_true_labels, politifact_predicted_labels)

politifact_conf_matrix = confusion_matrix(politifact_true_labels, politifact_predicted_labels)

tn, fp, fn, tp = politifact_conf_matrix.ravel()
politifact_specificity = tn / (tn + fp)

print(f"Accuracy on Politifact dataset: {politifact_accuracy:.4f}")
print(f"Recall on Politifact dataset: {politifact_recall:.4f}")
print(f"Specificity on Politifact dataset: {politifact_specificity:.4f}")
print(f"Precision on Politifact dataset: {politifact_precision:.4f}")
print(f"F1 Score on Politifact dataset: {politifact_f1_score:.4f}")
print("Confusion Matrix (Politifact dataset):")
print(politifact_conf_matrix)

Accuracy on Politifact dataset: 0.9949
Recall on Politifact dataset: 0.9991
Specificity on Politifact dataset: 0.9911
Precision on Politifact dataset: 0.9903
F1 Score on Politifact dataset: 0.9947
Confusion Matrix (Politifact dataset):
[[4654   42]
 [   4 4280]]
